# Generated by Django 5.2.7 on 2025-11-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_video', models.FileField(help_text='Upload the background video for the home page (MP4 recommended).', upload_to='site_assets/')),
                ('about_image', models.ImageField(help_text="Upload the image for the 'About Me' section.", upload_to='site_assets/')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
