# Generated by Django 5.2.7 on 2025-11-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0002_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='portfolio_videos/', verbose_name='Video File Upload (MP4)'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='portfolio_images/', verbose_name='Cover Image / Photo'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='External Video Link'),
        ),
    ]
